### ISSUE TITLE
Add PATCH method

### ISSUE THREAD

**Issue by adityabisoi** [adityabisoi/REST-fetch#1]
Currently, the project supports the following operations: `GET`

Add `PATCH` method to the existing `/users` endpoint.

The method should not manipulate the data in the database. It should send the same data that is incoming, with a positive response code.

**Comment by kaushik-rishi** [comment]
I would like to work on this issue one girlscript SoC starts.

**Comment by kaushik-rishi** [comment]
@adityabisoi Should the patch request actually change the resource in the DB or just check if a user with that id exists in  the DB and return the patched version based on the constrains ?

**Comment by kaushik-rishi** [comment]
I'd like to work on this issue @adityabisoi

**Comment by adityabisoi** [comment]
@kaushik-rishi None of the methods should actually change the date on the DB.

**Comment by kaushik-rishi** [comment]
Got it. Will work on this.

**Comment by namansamra** [comment]
I would like to work on this please assign it to me.

**Comment by kaushik-rishi** [comment]
@adityabisoi Any particular reason for using `promises` over `async await`?

**Comment by adityabisoi** [comment]
@namansamra This issue is already assigned. Please take up a different one.

**Comment by adityabisoi** [comment]
@kaushik-rishi Please ask your queries in the discord server.

**Comment by kaushik-rishi** [comment]
Okay. I couldn't find your ID I'll just ask in the projects section @adityabisoi

**Comment by adityabisoi** [comment]
Otherwise, you can start a discussion here https://github.com/adityabisoi/REST-fetch/discussions

**Comment by adityabisoi** [comment]
@kaushik-rishi I am closing the issue since the issue is outside the scope of the project, and assigning you a new one.

**Comment by adityabisoi** [comment]
@kaushik-rishi Are you working on this?

**Comment by kaushik-rishi** [comment]
Yes. I'm working on this.
But I need to add some fake user data which is a part of another issue which isn't resolved yet, So i made a 100 fake unique users.
I'll add the method soon.

**Comment by adityabisoi** [comment]
Unassigning @kaushik-rishi due to inactivity. This issue is open for new contributors.

**Comment by ritik307** [comment]
@adityabisoi hey, i would like to work on this issue.

**Comment by paramsiddharth** [comment]
> @adityabisoi @paramsiddharth hey, I would like to work on this issue.

You can start working on it! :) You'll be assigned as soon as #64 is merged.

**Comment by ritik307** [comment]
@paramsiddharth my PR has been merged can plz you assign me this issue now?

**Comment by paramsiddharth** [comment]
Done, @ritik307.
