### ISSUE TITLE
Add query params in songs route

### ISSUE THREAD

**Issue by ShauryaAg** [adityabisoi/REST-fetch#101]
Add route to fetch `songs` by their artist, language or genre.

### Requirements
- [ ] Add route with query param `/songs?artist=xyz`
- [ ] Add route with query param `/songs?genre=xyz`
- [ ] Add route with query param `/songs?language=xyz`

**Comment by ritik307** [comment]
@ShauryaAg @paramsiddharth I would like to work on this so kindly assign it.
