### ISSUE TITLE
Adding endpoints in books.ts

### ISSUE THREAD

**Issue by ritik307** [adityabisoi/REST-fetch#115]
**Describe the feature**
Adding following endpoints in `books.ts`
- [ ] /books?author=abc
- [ ] /books?price=123
- [ ] /books?name=xyz

**Are you working on this feature? (Yes)**

**Comment by ritik307** [comment]
@ShauryaAg @paramsiddharth I would like to work on this plz assign

**Comment by paramsiddharth** [comment]
@ritik307 Please go ahead.
