### ISSUE TITLE
Form to create new users 

### ISSUE THREAD

**Issue by rithgan** [adityabisoi/REST-fetch#12]
I think the project needs a form on a '/new' route to add(post) new users to the database. I am submitting wrt gssoc.

**Comment by rithgan** [comment]
If this issue gets approved I would also like it to be assigned to me

**Comment by hrushikesh-git** [comment]
@adityabisoi I would be glad if you assigned this issue to me and let me work on it

**Comment by rithgan** [comment]
@adityabisoi You have yet to assign this issue to me. Please do. I requested 2 days ago.

**Comment by adityabisoi** [comment]
The user should not have any method to manipulate the data on the server. The data on endpoints should be static and read-only.

**Comment by adityabisoi** [comment]
Please read the documentation for more instructions.
