### ISSUE TITLE
Adding products routes

### ISSUE THREAD

**Issue by ritik307** [adityabisoi/REST-fetch#122]
*Describe the feature*
Add `products` route with JSON having `name` `brand` `price` `image` `description` .

*Tasks Todo*
- [ ] Add  json file with appropiate data in `productData.json`.
- [ ] Add endpoint `/products` in `products.ts`.
- [ ] Add enpoint `/products/:id` in `products.ts`.

*Are you working on this feature? (Yes)*

**Comment by ritik307** [comment]
@ShauryaAg @paramsiddharth I would like to work on this issue plz assign

**Comment by paramsiddharth** [comment]
@ritik307 Yes, please! Go ahead.
