### ISSUE TITLE
Improvise animal routes with specialization

### ISSUE THREAD

**Issue by ritik307** [adityabisoi/REST-fetch#132]
*Describe the feature*
Improve animal routes specializing them based on animal kingdom hierarchy as follows:
![image](https://user-images.githubusercontent.com/22374829/116894352-952bc680-ac4f-11eb-9951-b29ae8e462d8.png)

Like, currently add `animals/amphibians` and `animals/amphibians/:id` with the following key-value pairs:
`type`, `breed`, `properities`, `imageUrl`, `description`

*Tasks Todo*
- [ ] Add  json file with appropiate data in `data/animals/amphibianData.json`
- [ ] Add endpoint `animals/amphibians` in `animals.ts`
- [ ] Add enpoint `animals/amphibians/:id` in `animals.ts`

*Are you working on this feature? (Yes)*

**Comment by ritik307** [comment]
@ShauryaAg @paramsiddharth I would like to work on this issue plz assign.

**Comment by paramsiddharth** [comment]
Yes, please. Go ahead, @ritik307 !
