### ISSUE TITLE
Extending animal route

### ISSUE THREAD

**Issue by ritik307** [adityabisoi/REST-fetch#136]
**Describe the feature**
Add the remaining `category` in the animal's route and fetching data about a particular type of animal.

**Describe the solution you'd like** :zap:

- [ ] add following categories- `bird`, `reptile`, `fish`.
- [ ] add endpoint `animals/:category?type=abc`

**Are you working on this feature? (Yes)**

**Comment by ritik307** [comment]
@paramsiddharth @ShauryaAg I would like to work on this issue, plz assign

**Comment by paramsiddharth** [comment]
@ritik307 Please go ahead!
