### ISSUE TITLE
Create homepage

### ISSUE THREAD

**Issue by subhangi2731** [adityabisoi/REST-fetch#142]
Create a homepage and add information about existing routes

**Comment by subhangi2731** [comment]
please assign me this issue

**Comment by adityabisoi** [comment]
@subhangi2731 Go ahead

**Comment by srishtij2000** [comment]
Can I work on this issue?

**Comment by subhangi2731** [comment]
@srishtij2000 I am working on this issue since I have opened this

**Comment by subhangi2731** [comment]
@adityabisoi I will send a pr by today

**Comment by paramsiddharth** [comment]
@subhangi2731 Are you still working on it?

**Comment by subhangi2731** [comment]
@paramsiddharth I am working on it I am making it everything totally from scratch thats why its taking time Yes i am doing it in react only will make a pr by tomorrow surely I will complete it

**Comment by paramsiddharth** [comment]
> tomorrow

No worries! If it is going to take long, you can create a draft PR and continue working so that we can keep reviewing and discussing the commits.

**Comment by subhangi2731** [comment]
@paramsiddharth okay will do it

**Comment by adityabisoi** [comment]
This issue has been stale for more than 10 days now. @paramsiddharth Please unassign @subhangi2731 if a PR is not raised by tonight.

**Comment by subhangi2731** [comment]
@adityabisoi i am sorry please forgive me

**Comment by paramsiddharth** [comment]
> @adityabisoi i am sorry please forgive me

There's nothing to apologize for, @subhangi2731 . Please create a draft PR if you haven't been able to complete it yet. We can keep track of the resolution.

**Comment by subhangi2731** [comment]
@paramsiddharth thank u for understanding I will create a pr by today anyhow if not then u can unassign me

**Comment by subhangi2731** [comment]
@adityabisoi @paramsiddharth I am facing merge conflicts in github workflows that is in linting I am not able to create a pr please check
![Screenshot from 2021-05-25 12-01-36](https://user-images.githubusercontent.com/53938490/119450160-270b8880-bd51-11eb-8ac8-8d04c7939062.png)

**Comment by subhangi2731** [comment]
@adityabisoi @paramsiddharth I am facing errors while creating a pr some conflicts please cehck what is this
![Screenshot from 2021-05-25 12-08-26](https://user-images.githubusercontent.com/53938490/119450712-f2e49780-bd51-11eb-89a5-c74d4d973d87.png)

**Comment by subhangi2731** [comment]
![Screenshot from 2021-05-25 12-55-10](https://user-images.githubusercontent.com/53938490/119456718-95a01480-bd58-11eb-88da-0d9ccc1fc756.png)

**Comment by subhangi2731** [comment]
@paramsiddharth @adityabisoi please check I am facing merge conflicts error while pulling the changes from main

**Comment by paramsiddharth** [comment]
@subhangi2731 Open the file `.github/workflows/linting.yml` and click `Accept Incoming Change`. Also, please make sure your PR is clean i. e. Not too many irrelevant/unexpected commits. Reply here if you face any further issues!

**Comment by subhangi2731** [comment]
![Screenshot from 2021-05-25 21-07-08](https://user-images.githubusercontent.com/53938490/119526744-47613480-bd9d-11eb-862b-72ad227614f0.png)

**Comment by subhangi2731** [comment]
@paramsiddharth where is the option of clicking accept Incoming change

**Comment by paramsiddharth** [comment]
> @paramsiddharth where is the option of clicking accept Incoming change

@subhangi2731 Hmmm... Doesn't look like there are any conflicts here.

At this point, I recommend you to start from a fresh fork because too many unknown conflicts will just make it harder for you to track errors. Clone a fresh fork and start the contribution there.

**Comment by subhangi2731** [comment]
@paramsiddharth I had done that thing only deleted the repo from local and forked and cloned once again. when i am pushing my changes it is showing like this
![Screenshot from 2021-05-26 07-42-39](https://user-images.githubusercontent.com/53938490/119592561-588a5f80-bdf6-11eb-8ed8-6fada99b5ef4.png)

**Comment by subhangi2731** [comment]
it is showing unable to access

**Comment by paramsiddharth** [comment]
> @paramsiddharth I had done that thing only deleted the repo from local and forked and cloned once again. when i am pushing my changes it is showing like this
> ![Screenshot from 2021-05-26 07-42-39](https://user-images.githubusercontent.com/53938490/119592561-588a5f80-bdf6-11eb-8ed8-6fada99b5ef4.png)

@subhangi2731 I think you accidentally cloned the main repository instead of your fork. Use:
```bash
git remote remove origin
git remote add origin https://github.com/subhangi2731/REST-fetch
git push -u origin homepage
```
