### ISSUE TITLE
 Add individual unit tests for individual endpoints

### ISSUE THREAD

**Issue by subhangi2731** [adityabisoi/REST-fetch#154]
I will add unit tests for each endpoints and do the testing

**Comment by subhangi2731** [comment]
@adityabisoi please assign this issue to me

**Comment by adityabisoi** [comment]
You may work on one endpoint at a time for this, since we have a lot of endpoints.

**Comment by subhangi2731** [comment]
@adityabisoi please help me here how to do unit test

**Comment by adityabisoi** [comment]
@subhangi2731 Sure, please discuss in the Discord channel
