### ISSUE TITLE
Adding the links of endpoints in frontend

### ISSUE THREAD

**Issue by subhangi2731** [adityabisoi/REST-fetch#155]
I will add the links of the API routes and the endpoints made in the project in frontend

**Comment by subhangi2731** [comment]
@adityabisoi please assign this issue to me

**Comment by adityabisoi** [comment]
@subhangi2731 Sure

**Comment by subhangi2731** [comment]
@adityabisoi please help me in this

**Comment by adityabisoi** [comment]
@subhangi2731 Sure, please discuss in the Discord channel
