### ISSUE TITLE
Dockerize the whole setup

### ISSUE THREAD

**Issue by ShauryaAg** [adityabisoi/REST-fetch#16]
### Description
 Currently, the setup consists of npm dependencies and mongodb to run the whole setup. MongoDB is required to download and setup separately. Dockerizing the whole setup will make it easier to focus on the development part and less on setting up.

Requirements:
- [ ] Create a Dockerfile to install npm dependencies and run the API
- [ ] Create a Dockerfile to setup MongoDB
- [ ] Create a docker-compose file to run both of those simultaneously

**Comment by jain-rishabh-21** [comment]
Assign it to me.
Discord username: krackerzzz#4371

**Comment by ShauryaAg** [comment]
@jain-rishabh-21 Sure.

**Comment by Bik-Krlvn** [comment]
I'll like to be assign if progress is stale

**Comment by jain-rishabh-21** [comment]
I am working on it @Bik-Krlvn ! Mp will raise a PR by tommorow!
