### ISSUE TITLE
Add unit test for route endpoint

### ISSUE THREAD

**Issue by subhangi2731** [adityabisoi/REST-fetch#164]
add unit tests for route endpoint

**Comment by subhangi2731** [comment]
@adityabisoi please assign this issue to me

**Comment by adityabisoi** [comment]
Part of #154 . Closing this issue. You can make PRs for testing without create similar issues.

**Comment by subhangi2731** [comment]
@adityabisoi u had only to create separate issues for different endpoints and now u closed it
