### ISSUE TITLE
Add ISSUE_TEMPLATE and PULL_REQUEST_TEMPLATE to the repository

### ISSUE THREAD

**Issue by ShauryaAg** [adityabisoi/REST-fetch#17]
Currently, the issues created can be absurd and may contain little to no information about it.
The pull requests have the same problem.

Add templates for both of them so that user knows what information to include while creating an issue or a pull request.

Requirements:
- [ ] Add template for Issues.
- [ ] Add template for pull requests.

**Comment by adityabisoi** [comment]
Issues for the issue template have already been created. Only include `PULL_REQUEST_TEMPLATE` in this issue.

**Comment by adityabisoi** [comment]
Related issues are already created. Closing this.
