### ISSUE TITLE
Remove functions which involve data manipulation

### ISSUE THREAD

**Issue by adityabisoi** [adityabisoi/REST-fetch#19]
We need to provide placeholder data to users, which should not be writable in any way. The data should be read-only.

Remove the `POST` and `DELETE` functionalities.

**Comment by subhangi2731** [comment]
please assign this issue to me

**Comment by adityabisoi** [comment]
@subhangi2731 Sure, please go ahead :)

**Comment by subhangi2731** [comment]
Sure I will
