### ISSUE TITLE
Add issue template: bug report

### ISSUE THREAD

**Issue by adityabisoi** [adityabisoi/REST-fetch#2]
Add an issue template for reporting bugs in the project.

**Comment by codewithvk** [comment]
Can you assign me @adityabisoi? ,

I will make PR When GSSOC starts.

**Comment by rithgan** [comment]
Hey, can this issue be assigned to me for gssoc? I noticed it was already assigned but there are no latest updates.

**Comment by adityabisoi** [comment]
@codewithvk Are you working on this?

**Comment by adityabisoi** [comment]
@rithgan Go ahead
