### ISSUE TITLE
Create homepage

### ISSUE THREAD

**Issue by adityabisoi** [adityabisoi/REST-fetch#21]
Create a homepage for the application, to show the supported endpoints of the application.

Note: Use a NodeJS templating engine, preferably Handlebars.

**Comment by rithgan** [comment]
I think pug or ejs would be better. Any specific reason for using handlebars?

**Comment by adityabisoi** [comment]
No, I said `preferably`.

**Comment by jain-rishabh-21** [comment]
Please assign it to me.
Discord username: krackerzzz#4371

**Comment by adityabisoi** [comment]
@jain-rishabh-21 Sure, go ahead!

**Comment by ShauryaAg** [comment]
@jain-rishabh-21 Please make a PR by tonight or you will unassigned. If you have any doubts feel free to ask them on the discord server.

**Comment by jain-rishabh-21** [comment]
Hey @ShauryaAg Was working on the dockerizing issue! Will resolve it in a day or two!

**Comment by ritik307** [comment]
@adityabisoi @ShauryaAg anyone working on this issue. If not then I am interested in working on this issue. Please assign.

**Comment by adityabisoi** [comment]
Unassigning @jain-rishabh-21 Assigning to @ritik307

**Comment by ritik307** [comment]
@adityabisoi thanks 🎉

**Comment by ritik307** [comment]
@adityabisoi can you give me a rough idea about how you want the page to look like? It will probably give me a little bit of clarity on how to approach.

**Comment by adityabisoi** [comment]
@ritik307 The homepage should give a brief intro on the project, and show all the currently supported endpoints (both for testing and placeholder endpoints). By testing, I am referring to `/users/` endpoint which has different methods. The page should show the demo data that should be sent and the data/response that should be gotten back.

Further doubts, please ask in the discord server/ DMs.

**Comment by ritik307** [comment]
@adityabisoi got it 😊
