### ISSUE TITLE
Add a /comments endpoint

### ISSUE THREAD

**Issue by adityabisoi** [adityabisoi/REST-fetch#22]
Add a `/comments` endpoint with a `GET` support, which should hold data as seen in comments on social media.

The fields should be `profile` with a hosted picture link, `name`, and `comment` with demo comments.

Hitting the endpoint `https://rest-fetch.herokuapp.com/comments/` must get the placeholder data.

Add 10 such demo data to the endpoint. The data should be provided as a JSON file, which would be imported at production.

**Comment by ahk4815** [comment]
@adityabisoi can i work on this?

**Comment by adityabisoi** [comment]
@ahk4815 Sure, go ahead

**Comment by ahk4815** [comment]
for accessing the request body in post requests, body parser module was required. Installing other modules is allowed @adityabisoi ?

**Comment by ahk4815** [comment]
The profile should be a hosted picture link, so what sort of link do i need to give here ? for example google link of an image will work?

**Comment by adityabisoi** [comment]
Discussions should rather be done in the Discord channel. This helps the threads here stay clean.

**Comment by ahk4815** [comment]
https://github.com/adityabisoi/REST-fetch/pull/54 
The PR for this issue has been added @adityabisoi

**Comment by ritik307** [comment]
@adityabisoi @paramsiddharth since the PR is pending for about 2 weeks, if no one is working on this issue can you kindly assign this to me.

**Comment by ahk4815** [comment]
I have updated the PR according to the changes requested @adityabisoi have a look
