### ISSUE TITLE
Add a /photos endpoint

### ISSUE THREAD

**Issue by adityabisoi** [adityabisoi/REST-fetch#23]
Add a `/photos` endpoint with a `GET` support.

The fields should be `picture` with a hosted picture link, and `name` with demo names.

Hitting the endpoint `https://rest-fetch.herokuapp.com/photos/` must get the placeholder data.

Add 10 such demo data to the endpoint. The data should be provided as a JSON file, which would be imported at production.

**Comment by AnshMishra2001** [comment]
Can I work on this issue?

**Comment by EANimesha** [comment]
still working on the issue? if you never mind, I like to work on it?

**Comment by adityabisoi** [comment]
@AnshMishra2001 Are you on this?

**Comment by AnshMishra2001** [comment]
Yes

**Comment by ShauryaAg** [comment]
@AnshMishra2001 Please make a PR by tonight or you will unassigned. If you have any doubts feel free to ask them on the discord server.

**Comment by adityabisoi** [comment]
Unassigning @AnshMishra2001 due to inactivity. This issue is open for new contributors.

**Comment by EANimesha** [comment]
Can I work on this issue?

**Comment by paramsiddharth** [comment]
PR #56 resolves this issue.
