### ISSUE TITLE
Add a /tasks endpoint

### ISSUE THREAD

**Issue by adityabisoi** [adityabisoi/REST-fetch#24]
Add a `/tasks` endpoint with a `GET` support.

The fields should be `task_name` with names of some everyday tasks, and `details` with the details of the task to be done.

Hitting the endpoint `https://rest-fetch.herokuapp.com/tasks/` must get the placeholder data.

Add 10 such demo data to the endpoint. The data should be provided as a JSON file, which would be imported at production.

**Comment by rithgan** [comment]
Can I work on this?

**Comment by rithgan** [comment]
Why is this issue still open if it got merged?
