### ISSUE TITLE
Add issue template: feature request

### ISSUE THREAD

**Issue by adityabisoi** [adityabisoi/REST-fetch#3]
Add an issue template for requesting new features in the project.

**Comment by subhangi2731** [comment]
Please assign this issue to me? @adityabisoi

**Comment by adityabisoi** [comment]
@subhangi2731 One issue at a time

**Comment by Anjali041** [comment]
Please assign this to me. I am GSSoC participant.

**Comment by adityabisoi** [comment]
@Anjali041 Go ahead
