### ISSUE TITLE
Tech Stack Update ( LOGO add )

### ISSUE THREAD

**Issue by rohank2502** [adityabisoi/REST-fetch#30]
I will like to add tech stack logo used in our project this will make our project attractive !! Will start to work on this issue as soon as i get assigned !!

**Comment by adityabisoi** [comment]
@rohank2502 That would be great! Go ahead!

**Comment by rohank2502** [comment]
Which tech stacks will you like to get updated ?

**Comment by adityabisoi** [comment]
@rohank2502 It would be convenient if discussions are done in the Discord server!
