### ISSUE TITLE
Adding Contributor section in readme  ( Automatically )

### ISSUE THREAD

**Issue by rohank2502** [adityabisoi/REST-fetch#31]
I will like to add a feature this will update contributor list in read me automatically !! Will start to work on this issue as soon as i get assigend !!

**Comment by adityabisoi** [comment]
Complete the previous issue first!

**Comment by rohank2502** [comment]
> 
> 
> Complete the previous issue first!

Sorry For delay I have done the PR Please have a look for that

**Comment by adityabisoi** [comment]
@rohank2502 You can go ahead
