### ISSUE TITLE
Add POST method

### ISSUE THREAD

**Issue by adityabisoi** [adityabisoi/REST-fetch#37]
Add `POST` method to `/users` endpoint.

The method **should not** allow the request to manipulate any data on the database. Instead, the data sent by the user should be returned exactly as it is, with an additional field `timestamp` with the current timestamp, and a positive response code `200`

**Comment by EANimesha** [comment]
I am a gssoc participant. I like to work on this issue.

**Comment by Bik-Krlvn** [comment]
I'll like to work on this

**Comment by adityabisoi** [comment]
@Bik-Krlvn This issue is taken already!

**Comment by subhangi2731** [comment]
can I work on this issue?

**Comment by ritik307** [comment]
@adityabisoi @paramsiddharth @ShauryaAg I would like to work on this Kindly assign

**Comment by paramsiddharth** [comment]
@EANimesha Are you working on the PR?

**Comment by adityabisoi** [comment]
@paramsiddharth Please assign this issue to @ritik307 if @EANimesha does not respond by today.
