### ISSUE TITLE
Add pull request template

### ISSUE THREAD

**Issue by adityabisoi** [adityabisoi/REST-fetch#4]
Add a pull request template to the project.

**Comment by subhangi2731** [comment]
Can I work on this? @adityabisoi

**Comment by adityabisoi** [comment]
@subhangi2731 Go ahead

**Comment by subhangi2731** [comment]
Can you assign this issue to me for gssoc @adityabisoi

**Comment by adityabisoi** [comment]
@subhangi2731 go ahead
