### ISSUE TITLE
Add PATCH method

### ISSUE THREAD

**Issue by adityabisoi** [adityabisoi/REST-fetch#40]
Add `PATCH` method to `/users` endpoint.

The method **should not** allow the request to manipulate any data on the database. Instead, the data sent by the user should be returned exactly as it is, with an additional field `timestamp` with the current timestamp, and a positive response code `200`

**Comment by subhangi2731** [comment]
can you assign this to me?

**Comment by adityabisoi** [comment]
@subhangi2731 Sure go ahead

**Comment by ShauryaAg** [comment]
@subhangi2731 Please make a PR by tomorrow or you will unassigned. If you have any doubts feel free to ask them on the discord server.

**Comment by subhangi2731** [comment]
I will make the pr by today

**Comment by adityabisoi** [comment]
Sure.
