### ISSUE TITLE
[GSSOC'21] Improve README.md 

### ISSUE THREAD

**Issue by ritik307** [adityabisoi/REST-fetch#43]
**Describe the feature**
Improving README.md with proper documentation and appealing UI

**Is your feature request related to a problem? Please describe.** :bulb:
A clear and concise description of what the problem is. 

**Describe the solution you'd like** :zap:
Would like to improve the documentation as it still has some knowledge gaps in understanding the project and also would like to make it a little bit more appealing.

**Are you working on this feature? (Yes)**

**Comment by ritik307** [comment]
@adityabisoi  I would like to work on this feature. Kindly assign me this issue

**Comment by adityabisoi** [comment]
@ritik307 Sure, make the README as nice as possible!

**Comment by ritik307** [comment]
@adityabisoi thanks! will start working on it right away.
