### ISSUE TITLE
Move all the models into a separate directory

### ISSUE THREAD

**Issue by ShauryaAg** [adityabisoi/REST-fetch#45]
Currently, the user models lies in `api/routes` folder. A separate directory should be created for all the models

Requirements:
- [ ] Move `user.ts` in a separate `models/` directory.
- [ ] Fix all the `user` imports

**Comment by Samridhi-98** [comment]
I would like to work on this issue, will you please assign me this.

**Comment by ShauryaAg** [comment]
@Samridhi-98 Sure. Go ahead.

**Comment by Samridhi-98** [comment]
> @Samridhi-98 Sure. Go ahead.

Thank you.
