### ISSUE TITLE
populate /users endpoint

### ISSUE THREAD

**Issue by adityabisoi** [adityabisoi/REST-fetch#5]
Populate `/users` endpoint with **fake** data

**Comment by paramsiddharth** [comment]
Does this involve storing fake data in a separate file and inserting it via Mongoose at deployment?

**Comment by adityabisoi** [comment]
@paramsiddharth Yes.

**Comment by subhangi2731** [comment]
Can you please assign this issue to me @adityabisoi I want to work on this

**Comment by adityabisoi** [comment]
@subhangi2731 One issue at a time.

**Comment by Sukriti-sood** [comment]
@adityabisoi Can you assign it to me

**Comment by adityabisoi** [comment]
@Sukriti-sood Go ahead

**Comment by Faizanrz7** [comment]
@adityabisoi Can you assign it to me as a part of gssoc'21 ?

**Comment by Sukriti-sood** [comment]
@adityabisoi I have made changes in PR ,Please have a look again
