### ISSUE TITLE
Add Users Delete endpoints

### ISSUE THREAD

**Issue by EANimesha** [adityabisoi/REST-fetch#50]
**Add User Delete endpoints**

- Add a users/:id endpoint with DELETE support.

**Are you working on this feature? Yes**
Please assign it to me

**Comment by adityabisoi** [comment]
I do not think getting users by ID would be necessary in any way. The `DELETE` method should be implemented. But as mentioned clearly in the documentation, it should not manipulate the data on database. So the method should fake the deletion. Implement on the `/users` endpoint, returning an empty string and `204` code.
