### ISSUE TITLE
Add local MongoDB setup instructions

### ISSUE THREAD

**Issue by paramsiddharth** [adityabisoi/REST-fetch#57]
Update `README.md` with instructions on how to set up a local MongoDB server instead of using an Atlas URI for development. This will speed up development by avoiding the need of an active Internet connection for database access.

Make sure to include command-line instructions on setting up a server using the Mongo Daemon (`mongod`).

**Comment by AshuKV** [comment]
Can I work on this issue under GSSoC'21? Kindly assign it to me.

**Comment by paramsiddharth** [comment]
Sure! Go ahead, @AshuKV .

**Comment by paramsiddharth** [comment]
@AshuKV Are you still working on it?

**Comment by AshuKV** [comment]
Hey @paramsiddharth I am still working on it, will push the code by today.

**Comment by subhangi2731** [comment]
If this issue is open, can I work on this?

**Comment by paramsiddharth** [comment]
> If this issue is open, can I work on this?

Sure, go ahead. If @AshuKV doesn't update the PR in time, yours is welcome.
