### ISSUE TITLE
Add github action to auto label issues

### ISSUE THREAD

**Issue by muthuannamalai12** [adityabisoi/REST-fetch#59]
Add GitHub action to auto label issues with gssoc21 label when contributor asks to work under gssoc21.

**Comment by paramsiddharth** [comment]
@muthuannamalai12 Please explain it further. And would you like it to be assigned to you?

**Comment by muthuannamalai12** [comment]
> @muthuannamalai12 Please explain it further. And would you like it to be assigned to you?

Whenever a user raises an issue GitHub action will automatically add the GSSOC21 label. I would love to work on this issue. Kindly assign it to me.

**Comment by paramsiddharth** [comment]
> > @muthuannamalai12 Please explain it further. And would you like it to be assigned to you?
> 
> Whenever a user raises an issue GitHub action will automatically add the GSSOC21 label. I would love to work on this issue. Kindly assign it to me.

Will it do that for all issues? Shouldn't it be selectively done only to issues that reference GSSoC'21?

**Comment by muthuannamalai12** [comment]
> > > @muthuannamalai12 Please explain it further. And would you like it to be assigned to you?
> > 
> > 
> > Whenever a user raises an issue GitHub action will automatically add the GSSOC21 label. I would love to work on this issue. Kindly assign it to me.
> 
> Will it do that for all issues? Shouldn't it be selectively done only to issues that reference GSSoC'21?

If they specify it as "gssoc","gssoc21","GSSOC21","GSSOC" in issue description the bot adds GSSOC21 label

**Comment by paramsiddharth** [comment]
> > > > @muthuannamalai12 Please explain it further. And would you like it to be assigned to you?
> > > 
> > > 
> > > Whenever a user raises an issue GitHub action will automatically add the GSSOC21 label. I would love to work on this issue. Kindly assign it to me.
> > 
> > 
> > Will it do that for all issues? Shouldn't it be selectively done only to issues that reference GSSoC'21?
> 
> If they specify it as "gssoc","gssoc21","GSSOC21","GSSOC" in issue description the bot adds GSSOC21 label

Sounds good to me. You may proceed.
