### ISSUE TITLE
Create .editorconfig

### ISSUE THREAD

**Issue by paramsiddharth** [adityabisoi/REST-fetch#66]
Create a `.editorconfig` to ensure consistency in the code-style throughout the project. The configuration should match the majority of files in the project, id est The indentation-type, size, whether or not the EOF newlines are present, what EOL sequence is being used, et cetera.

[![image](https://user-images.githubusercontent.com/30315706/112937158-cd1d8680-9144-11eb-860f-c1f62deabfb2.png)](https://editorconfig.org/)

Additionally, update the README to include instructions on installing the EditorConfig extension in the IDE being used to ensure the configurations are in proper effect.

**Comment by himanshu007-creator** [comment]
what are the coding standards?

**Comment by paramsiddharth** [comment]
> what are the coding standards?

There aren't any at the moment! The contributor needs to generalize and infer that from the existing project files.

**Comment by rithgan** [comment]
Can i work on this?

**Comment by paramsiddharth** [comment]
> Can i work on this?

Yes, go ahead.
