### ISSUE TITLE
Add eslint and prettier configuration file

### ISSUE THREAD

**Issue by ShauryaAg** [adityabisoi/REST-fetch#68]
Define linting rules so that all the files are properly linted.

Requirements:
- [ ] Add `.eslintrc.json` and `.eslintignore` and add the linting rules
- [ ] Add `.prettierrc` and `.prettierignore` and add the linting rules
- [ ] Add `eslint` and `prettier` as `devDependencies` in `package.json`
- [ ] Add linting scripts to `package.json`

**Comment by Samridhi-98** [comment]
Please assign me this issue, I would like to work on it.

**Comment by ShauryaAg** [comment]
@Samridhi-98 Sure. Go ahead.

**Comment by Samridhi-98** [comment]
> @Samridhi-98 Sure. Go ahead.

Thank you.
