### ISSUE TITLE
Add github actions workflow to check linting

### ISSUE THREAD

**Issue by ShauryaAg** [adityabisoi/REST-fetch#72]
Add a github actions workflow that checks if the committed files are passing the linting checking put in place.

Requirements:
- [ ] Add a `.github/workflows/linting.yml` file that runs linting checks for any push/PR.

It should run the lint script declared [here](https://github.com/adityabisoi/REST-fetch/blob/main/package.json#L9)

**Comment by AshuKV** [comment]
Can I work on this issue under GSSoC'21? Kindly assign it to me.

**Comment by ShauryaAg** [comment]
@AshuKV Sure.

**Comment by adityabisoi** [comment]
@ShauryaAg Please unassign this issue if @AshuKV does not respond today.
