### ISSUE TITLE
When clicked on "try it out" (on readme), redirected to wrong URL

### ISSUE THREAD

**Issue by akshay1027** [adityabisoi/REST-fetch#74]
**Describe the bug -**
When clicked on "try it out" (on readme), redirected to the wrong URL,  a bracket is there at the end of the URL! Also, it helps if the link opens in another tab so that we can back to the codebase.

**Screenshots or screen recordings -**

![2021-04-03 (7)_LI](https://user-images.githubusercontent.com/65683151/113486635-8972a600-94d1-11eb-9696-66c38444e891.jpg)

**Comment by akshay1027** [comment]
i would like to solve this @ShauryaAg

**Comment by ShauryaAg** [comment]
Sure @akshay1027. Go ahead.
