### ISSUE TITLE
Cannot find module '../../views/data.js'

### ISSUE THREAD

**Issue by ritik307** [adityabisoi/REST-fetch#76]
**Describe the bug -**

**Steps To Reproduce the behaviour -**

1. Open a terminal window.
2. execute the command: `npm run dev`

**Expected behaviour -**
Should be able to start the server.

**Screenshots or screen recordings -**

![bug-report](https://user-images.githubusercontent.com/22374829/113599033-a9ce6c00-965b-11eb-8e68-ea74da005d34.PNG)

**System Information (please complete the following information):**
 - OS: Windows, Ubuntu

**Comment by ritik307** [comment]
@paramsiddharth @ShauryaAg  I would like to fix the bug.

**Comment by ShauryaAg** [comment]
Sure @ritik307. Go ahead!
