### ISSUE TITLE
Adding animals data and pictures

### ISSUE THREAD

**Issue by Samridhi-98** [adityabisoi/REST-fetch#78]
**Describe the feature**
Adding JSON data for animals representing different animals with their breeds and images

**Are you working on this feature? (Yes)**

**Comment by Samridhi-98** [comment]
@ShauryaAg  @paramsiddharth  I would like to work on this issue will you please assign me this.

**Comment by ritik307** [comment]
@ShauryaAg why there is no tag on this issue ?
