### ISSUE TITLE
Add a /breeds and /pictures endpoint to animals route.

### ISSUE THREAD

**Issue by ritik307** [adityabisoi/REST-fetch#84]
**Describe the feature**
Add an endpoint  `GET` breed of a particular animal in /animals route.
Add an endpoint  `GET` pictures of a particular animal in /animals route.

**Expected behaviour**
Return array of breeds of a particular animal.
Return array of pictures of a particular animal.

**Are you working on this feature? (Yes)**

**Comment by ritik307** [comment]
@ShauryaAg  I would like to add this feature will you plz assign me this issue.

**Comment by paramsiddharth** [comment]
@ritik307 Go ahead!
