### ISSUE TITLE
Extend the /vehicles endpoint

### ISSUE THREAD

**Issue by Samridhi-98** [adityabisoi/REST-fetch#85]
**Describe the feature**
Add endpoints like **GET**  `vehicles/2`, 
Add endpoints like **GET** `vehicles?manufacturer=tata` .
`vehicles/2` will return 2 index record and `vehicles?manufacturer=tata`  will return manufacturer tata records from the JSON.

**Are you working on this feature? (Yes/No)**
Yes

**Comment by Samridhi-98** [comment]
@ShauryaAg  @paramsiddharth  I would like to add this feature, will you please assign it to me.

**Comment by paramsiddharth** [comment]
@Samridhi-98 Go ahead!
