### ISSUE TITLE
Adding endpoints to /photos

### ISSUE THREAD

**Issue by ritik307** [adityabisoi/REST-fetch#91]
**Describe the feature**
Adding index and fetch by group endpoints on /photos route.

**Describe the solution you'd like** :zap:
- [ ]  Add search by index endpoint that allows user to fetch photos based on their index.
- [ ]  Add group endpoint to photos that allow the user to fetch a certain number of photos from a particular index.

**Are you working on this feature? (Yes)**

**Comment by ritik307** [comment]
@paramsiddharth @ShauryaAg I would like to work on this feature so kindly assign me this issue.

**Comment by ShauryaAg** [comment]
Sure @ritik307. Go ahead!
