### ISSUE TITLE
Adding song route

### ISSUE THREAD

**Issue by ritik307** [adityabisoi/REST-fetch#96]
**Describe the feature**
Adding song route that provides details about the song name, songwriter, genre, link to the music video.

**Describe the solution you'd like** :zap:

- [ ] Add json file with appropiate data in `songData.json`.
- [ ] Add `/ route` - provides list of all the available songs.
- [ ] Add `/:id route` - provide the music details according to the given id.

**Are you working on this feature? (Yes)**

**Comment by ritik307** [comment]
@ShauryaAg @paramsiddharth  i would like to work on this issue plz assign it

**Comment by ShauryaAg** [comment]
Sure. Go ahead! @ritik307. However, why did you add `[C++]` tag in the front of this issue?

**Comment by ritik307** [comment]
@ShauryaAg sorry! my bad 😅😅
