### ISSUE TITLE
Adding routes info in the homepage

### ISSUE THREAD

**Issue by ritik307** [adityabisoi/REST-fetch#99]
**Describe the feature**
Add the following route info on the homepage.
- [ ] address route
- [ ] comments route
- [ ] songs route

**Are you working on this feature? (Yes)**

**Comment by ritik307** [comment]
@ShauryaAg @paramsiddharth i would like to work on this issue plz assign.

**Comment by paramsiddharth** [comment]
Thank you for the issue, @ritik307 . Please go ahead!
